# Generated by Django 5.1.4 on 2024-12-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('question', 'ip_address')},
        ),
    ]
